version: '3'

volumes:
  db_data:
  gems_data:

services:
  app:
    build: .
    command: ./script/puma-start.sh
    ports:
      - "3000:3000"
    volumes:
      - gems_data:/gems
      - .:/purple
    depends_on:
      - mysql
    stdin_open: true
    tty: true
  redis:
    image: redis:latest
  mysql:
    image: mysql:5.5.59
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tmp:/tmp
      - db_data:/var/lib/mysql
